### ISSUE TITLE
python-gi not installed

### ISSUE THREAD

**Issue by hezral** [ebruck/indicator-doom-cpu#1]
I got this when i tried to installed. I think python-gi is installed, on elementary OS Loki

Selecting previously unselected package indicator-doom-cpu.
(Reading database ... 269734 files and directories currently installed.)
Preparing to unpack indicator-doom-cpu-1.0.0-noarch.deb ...
Unpacking indicator-doom-cpu (1.0.0) ...
dpkg: dependency problems prevent configuration of indicator-doom-cpu:
 indicator-doom-cpu depends on python-gi; however:
  Package python-gi is not installed.

dpkg: error processing package indicator-doom-cpu (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.22-1ubuntu5.1+elementary2~ubuntu0.4.1) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160824-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Errors were encountered while processing:
 indicator-doom-cpu

**Comment by ebruck** [comment]
try:

sudo apt-get install -f

**Comment by hezral** [comment]
Thanks the install went through actually. Its just it showed that message.
