### ISSUE TITLE
Wide icon on Xfce

### ISSUE THREAD

**Issue by ghost** [ebruck/indicator-doom-cpu#3]
Not sure if anyone is checking this anymore, but on Xfce, the face is stretched and cut off.  Any way to fix this?  Using Xubuntu 16.04

![image](https://cloud.githubusercontent.com/assets/6278400/24419982/cfc9fd24-13b6-11e7-9593-5ba37919a165.png)

**Comment by ebruck** [comment]
Xfce does not resize the icons like Ubuntu's Unity. You can manually resize them to 20x24. They are stored under the app's install folder (/usr/share/indicator-doom-cpu/icons).  Could you please file a bug against the appindicator plugin? It should really be the one doing the resizing.

**Comment by ghost** [comment]
Thanks for getting back. Actually figured that out a few minutes ago, it works fine.

Fun little tool.
